spring.application.name=paqueteria
---------------------------------
//Conexion a mi bd
spring.datasource.url=jdbc:postgresql://localhost:5432/paqueteria
spring.datasource.username=postgres
spring.datasource.password=0Admin1357

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

-------------------------------------
//Creacion de token

jwt.secret=clave-secreta-super-larga-que-nadie-mas-conoce-cambiar-en-produccion-1234567890
jwt.expiration=3600000

----------------------------------------
//Servicio de correos
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=431a0c1072f0f1
spring.mail.password=23ee4a0a8614ce
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

--------------------------------------
//Servicio  de Rabbitqm
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.amqp=DEBUG